name: 'Slopless Security Scan'
description: 'AI-powered security scanning for your codebase. Finds vulnerabilities, generates fixes, and comments on PRs.'
author: 'xors-software'

branding:
  icon: 'shield'
  color: 'purple'

inputs:
  license-key:
    description: 'Slopless license key (from https://slopless.work)'
    required: true
  path:
    description: 'Path to scan (relative to repo root)'
    required: false
    default: '.'
  fail-on-critical:
    description: 'Fail the workflow if CRITICAL vulnerabilities are found'
    required: false
    default: 'true'
  fail-on-high:
    description: 'Fail the workflow if HIGH vulnerabilities are found'
    required: false
    default: 'false'
  auto-fix:
    description: 'Generate fix suggestions for vulnerabilities'
    required: false
    default: 'true'
  cross-validate:
    description: 'Cross-validate HIGH/CRITICAL findings to reduce false positives'
    required: false
    default: 'true'
  output-format:
    description: 'Output format: markdown, json, or rich'
    required: false
    default: 'markdown'
  comment-on-pr:
    description: 'Post scan results as a PR comment'
    required: false
    default: 'true'

outputs:
  report:
    description: 'Path to the scan report file'
    value: ${{ steps.scan.outputs.report }}
  total-vulnerabilities:
    description: 'Total number of vulnerabilities found'
    value: ${{ steps.scan.outputs.total }}
  critical-count:
    description: 'Number of CRITICAL vulnerabilities'
    value: ${{ steps.scan.outputs.critical }}
  high-count:
    description: 'Number of HIGH vulnerabilities'
    value: ${{ steps.scan.outputs.high }}
  exit-code:
    description: 'Exit code (0 = pass, 1 = fail)'
    value: ${{ steps.scan.outputs.exit_code }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Slopless
      shell: bash
      env:
        GIT_TOKEN: ${{ github.token }}
      run: |
        pip install --quiet "git+https://x-access-token:${GIT_TOKEN}@github.com/xors-software/slopless-engine.git"

    - name: Run Slopless Scan
      id: scan
      shell: bash
      env:
        SLOPLESS_LICENSE_KEY: ${{ inputs.license-key }}
      run: |
        bash "${{ github.action_path }}/entrypoint.sh"

    - name: Comment on PR
      if: inputs.comment-on-pr == 'true' && github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const reportPath = '${{ steps.scan.outputs.report }}';

          if (!reportPath || !fs.existsSync(reportPath)) {
            console.log('No report file found, skipping PR comment');
            return;
          }

          const report = fs.readFileSync(reportPath, 'utf8');
          const total = '${{ steps.scan.outputs.total }}';
          const critical = '${{ steps.scan.outputs.critical }}';
          const high = '${{ steps.scan.outputs.high }}';

          // Build comment body
          let body = '## Slopless Security Scan\n\n';

          if (total === '0') {
            body += '**No vulnerabilities found.** Your code looks clean.\n';
          } else {
            body += report + '\n';
          }

          body += '\n---\n*Powered by [Slopless](https://slopless.work)*';

          // Find existing comment to update
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const botComment = comments.find(c =>
            c.body.includes('## Slopless Security Scan')
          );

          if (botComment) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: botComment.id,
              body: body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body,
            });
          }

    - name: Check thresholds
      if: always()
      shell: bash
      run: |
        critical=${{ steps.scan.outputs.critical }}
        high=${{ steps.scan.outputs.high }}

        if [[ "${{ inputs.fail-on-critical }}" == "true" && "${critical:-0}" -gt 0 ]]; then
          echo "::error::Found ${critical} CRITICAL vulnerabilities"
          exit 1
        fi

        if [[ "${{ inputs.fail-on-high }}" == "true" && "${high:-0}" -gt 0 ]]; then
          echo "::error::Found ${high} HIGH vulnerabilities"
          exit 1
        fi

        echo "Threshold check passed"
